# Generated by Django 3.2.7 on 2021-09-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_tag_tagtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='content',
            new_name='simulado',
        ),
        migrations.RemoveField(
            model_name='note',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
