# Generated by Django 3.2.7 on 2021-09-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210927_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tagTitle',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
