# Generated by Django 3.2.7 on 2021-09-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_note_simulado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True, default=None, null=True)),
                ('sobrenome', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
